#!/bin/sh

echo '============================================='
echo '        Arch Linux Post-Installation         '
echo '============================================='
echo

USER=$(whoami)

echo '🖥️ What GPU are you using?'
echo '[1] Intel'
echo '[2] Nvidia'
echo '[3] AMD'

read -p '👉 ' GPU
echo

if ! builtin type -p 'yay' >/dev/null 2>&1; then
  CWD=`pwd`
  echo '🥣 Installing yay..'
  tmpdir="$(command mktemp -d)"
  command cd "${tmpdir}" || return 1
  sudo pacman -Sy --needed --noconfirm base base-devel git >/dev/null 2>&1
  git clone https://aur.archlinux.org/yay-bin.git >/dev/null 2>&1
  cd yay-bin
  makepkg -si <<< 'yes' >/dev/null 2>&1
  cd $CWD
  rm -rf "${tmpdir}"
  echo '🎉 yay installed!'
  echo
fi

case $GPU in
  1)
    echo '🔧 Installing Intel drivers...'
    yay -Sy --noconfirm xf86-video-intel vulkan-intel >/dev/null 2>&1
    echo '🎉 Intel drivers installed!'
    ;;
  2)
    echo '🔧 Installing Nvidia drivers...'
    yay -Sy --noconfirm nvidia nvidia-utils nvidia-settings nvidia-dkms nvidia-prime >/dev/null 2>&1
    echo '🎉 Nvidia drivers installed!'
    ;;
  3)
    echo '🔧 Installing AMD drivers...'
    yay -Sy --noconfirm xf86-video-amdgpu mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon >/dev/null 2>&1
    echo '🎉 AMD drivers installed!'
    ;;
esac

echo
echo '📦 Installing base packages...'
yay --noconfirm >/dev/null 2>&1
# remove i3lock because we will use betterlockscreen
yay -R --noconfirm i3lock >/dev/null 2>&1
echo '🎉 Base packages installed!'
echo

echo '📦 Installing own packages...'
packages=$(curl -Lks https://raw.githubusercontent.com/rabume/arch-post-install/main/packages.csv | tail -n +2 | cut -d, -f1)
total_packages=$(echo "$packages" | wc -l)
current_package=1

while IFS= read -r package; do
  printf "[%s/%s] Installing %-30s\r" "$current_package" "$total_packages" "$package"
  yay -Sy --noconfirm "$package" >/dev/null 2>&1
  current_package=$((current_package + 1))
done <<< "$packages"

echo
echo '🎉 Own packages installed!'
echo

echo '🔧 Download and setup dotfiles...'
git clone https://github.com/rabume/dotfiles.git $HOME/dotfiles >/dev/null 2>&1
cd $HOME/dotfiles
stow --adopt .
cd $CWD
echo '🎉 Dotfiles setup complete!'
echo

echo
echo '🏠 Setup home directory...'
mkdir -p $HOME/Pictures/wallpaper
mkdir -p $HOME/Downloads
mkdir -p $HOME/Development
echo '🎉 Home directory setup complete!'
echo

echo '🔧 Setup services...'
# Docker
sudo systemctl start docker.service >/dev/null 2>&1
sudo systemctl enable docker.service >/dev/null 2>&1
sudo groupadd docker >/dev/null 2>&1
sudo usermod -aG docker $USER >/dev/null 2>&1
echo '🎉 Docker setup complete!'
# Bluetooth
sudo systemctl start bluetooth.service >/dev/null 2>&1
sudo systemctl enable bluetooth.service >/dev/null 2>&1
echo '🎉 Bluetooth setup complete!'
# Cups
sudo systemctl start cups >/dev/null 2>&1
sudo systemctl enable cups >/dev/null 2>&1
echo '🎉 Cups setup complete!'
# SSH
sudo systemctl start sshd >/dev/null 2>&1
sudo systemctl enable sshd >/dev/null 2>&1
echo '🎉 SSH setup complete!'
echo

echo '🔧 Set up theme...'
gsettings set org.gnome.desktop.interface color-scheme prefer-dark >/dev/null 2>&1
gsettings set org.gnome.desktop.interface gtk-theme Catppucin-Mocha-Standard-Lavender-Dark >/dev/null 2>&1

# create syslinks for theme
ln -sf "/usr/share/themes/Catppuccin-Mocha-Standard-Lavender-Dark/gtk-4.0/gtk-dark.css" "/home/$USER/.config/gtk-4.0/gtk-dark.css" >/dev/null 2>&1
ln -sf "/usr/share/themes/Catppuccin-Mocha-Standard-Lavender-Dark/gtk-4.0/gtk.css" "/home/$USER/.config/gtk-4.0/gtk.css" >/dev/null 2>&1
ln -sf "/usr/share/themes/Catppuccin-Mocha-Standard-Lavender-Dark/gtk-4.0/assets" "/home/$USER/.config/gtk-4.0/assets" >/dev/null 2>&1

echo '🎉 Theme setup complete!'
echo

echo '🔧 Setup development tools...'

# g
curl -sSL https://git.io/g-install | sh -s -- bash fish -y >/dev/null 2>&1
echo '🎉 Go setup complete!'

# nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
echo '🎉 NVM setup complete!'

# bun
curl -fsSL https://bun.sh/install | bash
echo '🎉 Bun setup complete!'

# pyenv
curl https://pyenv.run | bash
echo '🎉 Pyenv setup complete!'
fish -c "set -Ux PYENV_ROOT $HOME/.pyenv"
fish -c "fish_add_path $PYENV_ROOT/bin"

# git profile
go install github.com/dotzero/git-profile@latest >/dev/null 2>&1
echo '🎉 Git profile setup complete!'
echo

echo '🐚 Shell setup...'
fish -c "curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher"
fish -c "fisher install FabioAntunes/fish-nvm edc/bass"

PASSWORD=""
read -s -p '🔑 Enter your user password: ' PASSWORD
chsh -s /bin/fish <<< $PASSWORD
echo '🎉 shell setup complete!'
echo

echo '🧹 Clear pacman and yay cache'
yay -Sc --noconfirm - 2>/dev/null
rm -rf ~/.cache/yay/* - 2>/dev/null
rm -rf ~/.cache/go-build/* - 2>/dev/null
sudo rm -rf /var/cache/pacman/pkg/* - 2>/dev/null
echo '🎉 Cache cleared!'
echo

echo
echo '###################################################'
echo '##                                               ##'
echo '##          👏 Installation Complete             ##'
echo '##      reboot to use the new configurations     ##'
echo '##                                               ##'
echo '###################################################'
echo
